<template>
  <div class="mx-auto w-full max-w-7xl px-5 py-10 sm:px-8 lg:py-14">
    <div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p class="section-kicker">Workspace overview</p><h1 class="mt-2 text-4xl font-bold tracking-[-0.04em] text-slate-950">Welcome back.</h1><p class="mt-3 text-slate-500">Your completed work and quick actions, in one focused view.</p></div><router-link to="/#tools" class="primary-button">New conversion <ArrowUpRight :size="16" /></router-link></div>
    <div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div v-for="stat in stats" :key="stat.label" class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-slate-500">{{ stat.label }}</span><component :is="stat.icon" :size="18" class="text-cobalt" /></div><p class="mt-5 text-3xl font-bold tracking-tight text-slate-950">{{ stat.value }}</p><p class="mt-1 text-xs font-semibold text-emerald-600">{{ stat.note }}</p></div></div>
    <div class="mt-8 grid gap-8 lg:grid-cols-[1.4fr_.8fr]"><section class="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div class="flex items-center justify-between"><div><p class="section-kicker">Activity</p><h2 class="mt-2 text-xl font-bold text-slate-950">Recent conversions</h2></div><span class="text-xs font-semibold text-slate-400">Stored on this device</span></div><div v-if="history.length" class="mt-6 divide-y divide-slate-100"><div v-for="job in history" :key="job.id" class="flex items-center gap-3 py-4 first:pt-0 last:pb-0"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-cobalt"><FileText :size="18" /></span><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold text-slate-800">{{ job.name }}</p><p class="mt-1 text-xs text-slate-400">{{ job.tool }} · {{ formatDate(job.completedAt) }}</p></div><a v-if="job.id" :href="downloadUrl(job.id)" class="text-xs font-bold text-cobalt hover:underline">Download</a></div></div><div v-else class="empty-state mt-6 border-slate-200 bg-slate-50/50 py-12"><Clock3 :size="24" class="mx-auto text-slate-400" /><p class="mt-3 font-semibold text-slate-700">No completed conversions yet.</p><p class="mt-1 text-sm text-slate-500">Your finished document jobs will appear here.</p><router-link to="/#tools" class="mt-4 inline-flex text-sm font-bold text-cobalt">Choose a tool <ArrowRight :size="15" /></router-link></div></section><aside class="rounded-3xl bg-slate-950 p-7 text-white"><p class="text-xs font-bold uppercase tracking-[.16em] text-cobalt-200">Your plan</p><h2 class="mt-3 text-2xl font-bold">Free workspace</h2><p class="mt-3 text-sm leading-6 text-slate-300">Core conversions are ready to use. Sign-in and synced history can be connected in the next platform phase.</p><div class="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full w-[30%] rounded-full bg-[#6d8dff]" /></div><div class="mt-3 flex justify-between text-xs font-semibold text-slate-400"><span>{{ history.length }} local jobs</span><span>10 monthly limit</span></div><router-link to="/pricing" class="secondary-button mt-8 w-full justify-center">Compare plans <ArrowRight :size="16" /></router-link></aside></div>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowRight, ArrowUpRight, Clock3, FileCheck2, FileText, HardDrive } from '@lucide/vue'
import api from '../services/api'
import { readHistory, type HistoryItem } from '../data/history'
const history = ref<HistoryItem[]>([])
onMounted(() => { history.value = readHistory() })
const stats = computed(() => [{ label: 'Conversions', value: String(history.value.length), note: history.value.length ? 'Completed on this device' : 'Ready when you are', icon: FileCheck2 }, { label: 'Saved files', value: String(history.value.length), note: history.value.length ? 'Available from recent jobs' : 'No saved jobs yet', icon: HardDrive }, { label: 'Time saved', value: `${Math.max(0, history.value.length * 8)}m`, note: 'Estimated from completed jobs', icon: Clock3 }, { label: 'Favorites', value: '0', note: 'Add favorites after sign-in', icon: FileText }])
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function downloadUrl(id: string) { return `${api.defaults.baseURL}/jobs/${id}/download` }
</script>
