<template>
  <div class="mx-auto w-full max-w-6xl px-5 py-10 sm:px-8 lg:py-16">
    <div class="mb-8 flex items-center gap-2 text-sm text-slate-400"><router-link to="/" class="hover:text-cobalt">Tools</router-link><ChevronRight :size="15" /><span class="font-medium text-slate-600">{{ tool?.name || 'Tool' }}</span></div>
    <div v-if="!tool" class="rounded-3xl border border-slate-200 bg-white p-12 text-center"><h1 class="text-2xl font-bold">Tool not found</h1><router-link to="/" class="primary-button mx-auto mt-6">Back home</router-link></div>
    <div v-else class="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-start">
      <aside><span class="tool-icon tool-icon--large"><component :is="tool.icon" :size="26" /></span><p class="section-kicker mt-6">{{ tool.category }} tool</p><h1 class="mt-2 text-4xl font-bold tracking-[-0.04em] text-slate-950">{{ tool.name }}</h1><p class="mt-4 leading-7 text-slate-500">{{ tool.description }}</p><div class="mt-7 grid grid-cols-2 gap-3"><div class="meta-card"><span>Input</span><strong>{{ tool.input }}</strong></div><div class="meta-card"><span>Output</span><strong>{{ tool.output }}</strong></div></div><div class="mt-7 flex items-start gap-3 rounded-2xl bg-blue-50/70 p-4 text-sm leading-6 text-slate-600"><ShieldCheck :size="18" class="mt-0.5 shrink-0 text-cobalt" /><p>Files are processed for this job only. Completed jobs are remembered locally on this device.</p></div></aside>
      <section class="workspace-panel">
        <div class="flex items-center justify-between border-b border-slate-100 pb-5"><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Workspace</p><h2 class="mt-1 text-lg font-bold text-slate-900">Upload and process</h2></div><span class="status-chip"><span class="status-dot" /> Ready</span></div>
        <div v-if="status === 'IDLE'" class="pt-6">
          <div v-if="tool.options?.includes('degrees')" class="mb-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><label class="block text-xs font-bold uppercase tracking-[.13em] text-slate-500" for="degrees">Rotation angle</label><select id="degrees" v-model="options.degrees" class="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 sm:w-56"><option value="90">90 degrees</option><option value="180">180 degrees</option><option value="270">270 degrees</option></select></div>
          <div v-if="tool.options?.includes('extraction')" class="mb-5 rounded-2xl border border-[#d9e1fb] bg-[#f5f7ff] p-4"><div class="flex items-start gap-3"><div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-[#4164ea] shadow-sm"><Table2 :size="17" /></div><div class="min-w-0 flex-1"><label class="block text-xs font-bold uppercase tracking-[.13em] text-slate-500" for="extraction">Extraction mode</label><select id="extraction" v-model="options.extraction" class="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="auto">Adaptive — tables + full text</option><option value="tables">Tables only</option><option value="text">Full text only</option></select><label class="mt-3 flex items-center gap-2 text-xs font-semibold text-slate-600"><input v-model="options.include_text" type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#4164ea]" /> Keep the document text sheet</label><label class="mt-3 flex items-center gap-2 text-xs font-semibold text-slate-600"><input v-model="options.ocr_fallback" type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#4164ea]" /> OCR pages with missing or low-quality text</label><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold uppercase tracking-[.13em] text-slate-500">OCR language<select v-model="options.ocr_language" class="mt-2 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold normal-case tracking-normal"><option value="auto">Auto (eng + vie when installed)</option><option value="eng">English</option><option value="vie">Vietnamese</option><option value="eng+vie">English + Vietnamese</option></select></label><label class="flex items-center gap-2 self-end pb-2 text-xs font-semibold text-slate-600"><input v-model="options.use_canonical" type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#4164ea]" /> Use canonical audit pipeline</label></div></div></div></div>
          <div v-if="tool.options?.includes('pages')" class="mb-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><label class="block text-xs font-bold uppercase tracking-[.13em] text-slate-500" for="pages">Page selection</label><input id="pages" v-model="options.pages" class="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700" placeholder="Example: 1, 3-5" /><p class="mt-2 text-xs text-slate-400">Use page numbers and ranges separated by commas.</p></div>
          <FileUploader :accept="acceptForTool(tool)" :multiple="allowsMultiple(tool)" @files-selected="startConversion" /><p class="mt-5 text-center text-xs text-slate-400">Supported input: {{ tool.input }} · Maximum file size: 25 MB</p>
        </div>
        <div v-else-if="status === 'UPLOADING' || status === 'PROCESSING'" class="py-16 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-cobalt-50 text-cobalt"><LoaderCircle :size="28" class="animate-spin" /></div><h3 class="mt-6 text-xl font-bold text-slate-900">{{ status === 'UPLOADING' ? 'Uploading your files' : 'Processing your document' }}</h3><p class="mt-2 text-sm text-slate-500">{{ stageMessage }}</p><div class="mx-auto mt-8 max-w-sm"><div class="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>{{ status === 'UPLOADING' ? 'Uploading' : 'Working' }}</span><span>{{ progress }}%</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-cobalt transition-all duration-500" :style="{ width: `${progress}%` }" /></div></div></div>
        <div v-else-if="status === 'SUCCESS'" class="py-12 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-500"><CheckCircle2 :size="30" /></div><h3 class="mt-6 text-2xl font-bold text-slate-900">Your result is ready</h3><p class="mt-2 text-slate-500">{{ outputFilename || `OfficeFlow_${tool.output}` }}</p><div v-if="resultMetadata" class="mx-auto mt-6 max-w-xl rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left text-sm text-slate-600"><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><span><b class="block text-lg text-slate-900">{{ resultMetadata.pages || 0 }}</b>pages</span><span><b class="block text-lg text-slate-900">{{ resultMetadata.tables || 0 }}</b>tables</span><span><b class="block text-lg text-slate-900">{{ resultMetadata.ocr_pages || 0 }}</b>OCR pages</span><span><b class="block text-lg text-slate-900">{{ resultMetadata.low_confidence_count || 0 }}</b>low confidence</span><span><b class="block text-lg text-slate-900">{{ resultMetadata.facts_count || 0 }}</b>truth facts</span><span><b class="block text-lg text-slate-900">{{ resultMetadata.graph_edges_count || 0 }}</b>graph links</span></div><p class="mt-4">State: <b class="text-slate-900">{{ resultMetadata.document_state || 'unknown' }}</b><span v-if="resultMetadata.quality_dimensions?.overall != null"> · Overall quality: <b class="text-slate-900">{{ Math.round(resultMetadata.quality_dimensions.overall * 100) }}%</b></span></p><p v-if="resultMetadata.review_required" class="mt-2 text-amber-700">Review required: {{ resultMetadata.review_tasks?.length || 0 }} task(s) need verification against the source evidence.</p><p v-if="resultMetadata.warnings?.length" class="mt-2 text-amber-700">Review warnings: {{ resultMetadata.warnings.join('; ') }}</p><p v-else-if="!resultMetadata.review_required" class="mt-2 text-emerald-700">No processing warnings were reported.</p></div><ConfidenceReviewPanel v-if="resultMetadata?.review_tasks?.length" :tasks="resultMetadata.review_tasks" @verified="handleVerified" /><div class="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button class="primary-button justify-center" @click="downloadFile">Download {{ tool.output }} <Download :size="16" /></button><button class="secondary-button justify-center" @click="resetTool">Process another file <RotateCcw :size="16" /></button></div></div>
        <div v-else class="py-12 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-rose-50 text-rose-500"><AlertTriangle :size="29" /></div><h3 class="mt-6 text-2xl font-bold text-slate-900">We couldn't finish that job</h3><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-rose-600">{{ errorMessage }}</p><button class="secondary-button mx-auto mt-8 justify-center" @click="resetTool">Try again <RotateCcw :size="16" /></button></div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onUnmounted, reactive, ref } from 'vue'
import { AlertTriangle, CheckCircle2, ChevronRight, Download, LoaderCircle, RotateCcw, ShieldCheck, Table2 } from '@lucide/vue'
import { useRoute } from 'vue-router'
import api from '../services/api'
import FileUploader from '../components/upload/FileUploader.vue'
import ConfidenceReviewPanel from '../components/review/ConfidenceReviewPanel.vue'
import { allowsMultiple, acceptForTool, getTool } from '../data/tools'
import { saveHistory } from '../data/history'

const route = useRoute()
const tool = computed(() => getTool(route.params.slug as string))
const status = ref<'IDLE' | 'UPLOADING' | 'PROCESSING' | 'SUCCESS' | 'FAILED'>('IDLE')
const progress = ref(0)
const currentJobId = ref('')
const outputFilename = ref('')
const errorMessage = ref('')
const resultMetadata = ref<any>(null)
const options = reactive({ degrees: '90', pages: '', extraction: 'auto', include_text: true, ocr_fallback: true, ocr_language: 'auto', use_canonical: true })
let pollingInterval: number | null = null
const stageMessage = computed(() => status.value === 'UPLOADING' ? 'Preparing your files for the processing pipeline.' : `Running ${tool.value?.name || 'document'} and validating the output.`)

async function startConversion(files: File[]) {
  if (!files.length || !tool.value) return
  if (tool.value.options?.includes('pages') && !options.pages.trim()) { errorMessage.value = 'Please enter the pages you want to process.'; status.value = 'FAILED'; return }
  status.value = 'UPLOADING'; progress.value = 12; errorMessage.value = ''; resultMetadata.value = null
  const payload: Record<string, unknown> = { ...options }
  if (!tool.value.options?.includes('extraction')) delete payload.extraction
  if (!tool.value.options?.includes('pages')) delete payload.pages
  if (!tool.value.options?.includes('degrees')) delete payload.degrees
  const formData = new FormData(); formData.append('tool_slug', tool.value.slug); formData.append('options_json', JSON.stringify(payload)); files.forEach((file) => formData.append('files', file))
  try { const response = await api.post('/jobs/', formData, { headers: { 'Content-Type': 'multipart/form-data' } }); currentJobId.value = response.data.id; status.value = 'PROCESSING'; progress.value = 35; startPolling() }
  catch (error: any) { status.value = 'FAILED'; errorMessage.value = error.response?.data?.detail || 'Upload failed. Please check the server and try again.' }
}
function startPolling() { if (pollingInterval) window.clearInterval(pollingInterval); pollingInterval = window.setInterval(async () => { try { const response = await api.get(`/jobs/${currentJobId.value}`); progress.value = response.data.progress; if (response.data.status === 'SUCCESS') { status.value = 'SUCCESS'; outputFilename.value = response.data.output_filename || ''; resultMetadata.value = response.data.result_metadata || null; saveHistory({ id: currentJobId.value, name: response.data.original_filename, tool: tool.value?.name || 'Document tool', output: response.data.output_filename || '', completedAt: new Date().toISOString() }); window.clearInterval(pollingInterval!) } if (response.data.status === 'FAILED') { status.value = 'FAILED'; errorMessage.value = response.data.error_message || 'The processing job failed.'; window.clearInterval(pollingInterval!) } } catch { status.value = 'FAILED'; errorMessage.value = 'The connection was interrupted. Please try again.'; window.clearInterval(pollingInterval!) } }, 1200) }
function downloadFile() { if (currentJobId.value) window.location.href = `${api.defaults.baseURL}/jobs/${currentJobId.value}/download` }
function handleVerified(payload: { task: unknown; verifiedValue: string }) { console.info('verified review value', payload) }
function resetTool() { if (pollingInterval) window.clearInterval(pollingInterval); status.value = 'IDLE'; progress.value = 0; currentJobId.value = ''; outputFilename.value = ''; resultMetadata.value = null; errorMessage.value = '' }
onUnmounted(() => { if (pollingInterval) window.clearInterval(pollingInterval) })
</script>
